### ISSUE TITLE
Provided private key and latest private key fingerprints mismatch.

### ISSUE THREAD

**Issue by pgeorgiev333** [JFrogDev/artifactory-docker-examples#12] opened 2017-03-09 14:34 UTC
I have no idea where to post this but doe anyone have an idea what is wrong and why artifactory fails to start?

09-Mar-2017 11:21:41.912 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.artifactory.webapp.servlet.AccessServerStarter
 java.lang.IllegalStateException: Provided private key and latest private key fingerprints mismatch. provided: 69bb6f7139e10fb1451354742734019fb8b76bb0a1b7ac66d11ded1d0671356c, latest: 72eb1d3af1a9035a7069450c0de547fded00575f856becc78d799ab86bbcb4c6
        at org.jfrog.access.server.AccessServerBootstrap.verifyLatestPrivateKey(AccessServerBootstrap.java:251)
        at org.jfrog.access.server.AccessServerBootstrap.copyPrivateKeyAndCertFromBootstrapIfExists(AccessServerBootstrap.java:210)
        at org.jfrog.access.server.AccessServerBootstrap.initPrivateKeyAndCert(AccessServerBootstrap.java:128)
        at org.jfrog.access.server.AccessServerBootstrap.<init>(AccessServerBootstrap.java:80)
        at org.artifactory.webapp.servlet.AccessServerStarter.startAccessServer(AccessServerStarter.java:51)
        at org.artifactory.webapp.servlet.AccessServerStarter.contextInitialized(AccessServerStarter.java:34)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:587)
        at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by eldada** [comment] 2017-03-09 16:35
Hi @pgeorgiev333 . Can you provide more details?
- What did you install?
- Are these based on the examples here?
- What are the steps you took. Help us reproduce to try and help.

**Comment by pgeorgiev333** [comment] 2017-03-10 07:45
well i started artifactory 4.x and used it for a while with volumes for /etc/ , data/ , backup/ and logs/ folders. 
Then i chnaged the image to 5.1 and everything was ok for a while. Today i upgraded docker engine to the latest release 17.03.0-ce and artifactory failed to start. This is the error that i see in the logs.

I searched google and i could not find even one result that contains this error. I had to delete the data in the volumes and start from scratch. But it's annoying that there is not a single google result for that error and it does not make any sense to me (as artifactory is not using SSL on the listeners...)

Any hints will be appreciated. I logged the issue here as i have no idea where to log it.

Thanks

**Comment by eldada** [comment] 2017-03-12 10:19
This error is from a fairly new feature in Artifactory, noting that the already registered key (in DB) is not matching the new key found on file system.
This sounds like there was a change in the mount volume used by Artifactory after the Docker upgrade.
This caused Artifactory to recreate an access key, and it does not match the already registered one in DB.
Are you aware that on 5.X, there is now a single mount volume for all data + config?

I can't find a reason why it will happen after the docker upgrade...

**Comment by pgeorgiev333** [comment] 2017-03-13 06:41
Yes, am aware (i read it after the error). What i did was to keep the 4 volumes, stop/delete the 4.x container, change the image to the 5.x container and start it. Then it was working untill i had to stop docker to upgrade it. When i started artifactory after the docker upgrade it did not work.

SO i was forced to delete all 4 volumes, create a single one and move on. It would be nice to add some documentation on this feature and what do to when you hit this error.

Thanks

**Comment by eldada** [comment] 2017-03-13 07:07
You are right - this should be better documented!
I will work on improving our Wiki and also add a note about the error you enountered.
Last request - can you share the command line you used to run Artifactory 4 and the 5? I want to confirm the cause.

**Comment by pgeorgiev333** [comment] 2017-03-13 07:44
I just use docker compose:

 artifactory:
  image: docker.bintray.io/jfrog/artifactory-oss:5.1.0
  container_name: artifactory
  mem_limit: 12g
  memswap_limit: 12g
  restart: always
  environment:
  - TERM=linux
  ports:
  - "8081:8081"
  volumes:
  - /docker/artifactory/:/var/opt/jfrog/artifactory


The docker-compose section for the 4.x version is the same except:
1. I specified 4 volumes
2. The version of the image was 4.xx

Thanks

**Comment by eldada** [comment] 2017-03-15 12:07
@pgeorgiev333  - I wanted to let you know we are documenting a recovery process for such an error, so it will come up in formal searches in our Wiki.
We were unable to reproduce your error, but are still working on trying to figure it our.
Once documentation is ready, I will close this issue.

**Comment by pgeorgiev333** [comment] 2017-03-15 13:05
Thanks

**Comment by eldada** [comment] 2017-03-16 10:03
We have a formal documentation for this error now.
Look in https://www.jfrog.com/confluence/display/RTF/Access+Tokens#AccessTokens-Troubleshooting

Closing.

**Closed by eldada** 2017-03-16 10:03 UTC

**Comment by pgeorgiev333** [comment] 2017-03-16 10:40
Awesome! Thanks

**Comment by elordahl** [comment] 2017-03-18 19:19
@eldada The troubleshooting has us save the keys from the "first Artifactory instance."  Where are the keys on that instance?  I'm attempting to upgrade from 4.16.1, and havent been able to get it started successfully.  Currently at the key-mismatch error, but am puzzled because the docs make it sound like the keys didnt exist in 4.x.

**Comment by elordahl** [comment] 2017-03-18 19:51
The troubleshooting worked once i set permissions properly on all the files referenced by the troubleshooting steps.  

On a related note, i'm happy that it's finally working, but encountered file-permission issues at about every step.  I'm not sure why.

Anyway, glad i found this!

**Comment by eldada** [comment] 2017-03-19 07:36
@elordahl - thanks for the feedback. I'll pass it on to try and improve the troubleshooting section.

**Comment by magnusart** [comment] 2017-05-25 22:14
@eldada Please add the directory where this access token is stored to the list at (and other places applicable) https://www.jfrog.com/confluence/display/RTF/Installing+Artifactory 

From what I gather it's `$ARTIFACTORY_HOME/access/etc/keys`?

**Comment by eldada** [comment] 2017-05-28 05:47
@magnusart - you can see it here: https://www.jfrog.com/confluence/display/RTF/Access+Tokens#AccessTokens-SettingthePrivateKeyandRootCertificate
Is this not enough?

**Comment by magnusart** [comment] 2017-05-28 06:21
@eldada I've been trying to set up Artifactory in a containerized environment. I'm not going to read through all available documentation in detail and piece together different failure scenarios. 

When I read the installation documentation that contains a directory structure title I expect to find all relevant folders on the root level with a comment. Access folder is not there.

**Comment by eldada** [comment] 2017-05-28 06:31
@magnusart - I agree. It should also be listed there. I will work on adding it.

**Comment by magnusart** [comment] 2017-05-28 06:33
Thanks! @eldada

**Comment by eldada** [comment] 2017-05-28 08:03
Done!

**Comment by fbouliane** [comment] 2017-06-13 17:07
We had the problem too :

This happened when you start artifactory 5 with the 4 volumes layout.
Artifactory starts and create a new ephemeral volumes with a /access folder containing keys that it migrates from somewhere.
As long as you don't restart the container, everything works fine.
 
When you restart the container after the migration, the /access cease to exists because the volume is ephemeral and unexpected issues arise. To solve it, we had to :
1. Move to the new "one volume" layout.
2. Import the /access folder from the deceased volume (/var/lib/docker/volumes/{VOLUME ID}/_data/access/etc/keys/) with the right chmod(important)

This way we didn't have to start from scratch

**Comment by eldada** [comment] 2017-06-13 18:49
Thx @fbouliane for the addition!
